spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery
    username: courier
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082
  servlet:
    context-path: /courier-service

app:
  integration:
    food-delivery:
      url: http://localhost:8080/food-delivery-service/
  food-delivery-service:
    username: courier
    password: password

message:
  courier-queue: courierQueue
  food-delivery-routing-key: message.fds.courier
  courier-routing-key: message.courier