spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery
    username: courier
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /courier-service

app:
  integration:
    food-delivery:
      url: http://localhost:8080/food-delivery-service/
  food-delivery-service:
    username: courier
    password: password